# da code

name: Meine CI Pipeline

on: push

env:
  MEINE_VARIABLE: asdf

jobs:
  tests:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        node-version: [13.x, 14.x, 15.x]
    env:
      MEINE_VARIABLE: asdfgh
    steps:
      - uses: actions/checkout@v2
        env:
          MEINE_VARIABLE: asdfghjkl
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm install -g yarn
      - run: yarn install
      - run: yarn run test
      - run: touch ${{ matrix.node-version }}.txt
        env:
          MEINE_GANZ_NORMALE_VARIABLE: ${{secrets.MEINE_GEHEIME_VARIABLE}}
      - name: Artefacts upload
        uses: actions/upload-artifact@v2
        with:
          name: My-Test-Artefacts
          path: ./*.txt
  deploy:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, 'skip ci')"
    needs: [tests]
    steps:
      - uses: actions/checkout@v2
        env:
          MEINE_VARIABLE: asdfghjkl
      - name: Use Node.js 15.x
        uses: actions/setup-node@v1
        with:
          node-version: 15.x
      - run: npm install -g yarn
      - run: yarn install
        
